/**
 * Telegram Agent Configuration — loaded from config/agents.json
 *
 * This file is auto-generated by `npm run setup` or manually edited.
 * Supports dynamic agent registration without code changes.
 */

import { readFileSync, writeFileSync, existsSync } from 'fs'
import { resolve } from 'path'
import { logger } from '../lib/logger.js'

export interface AgentConfig {
  name: string
  chatId: string
  userId: string
  displayName: string
  model: 'haiku' | 'sonnet' | 'opus'
}

interface AgentsFile {
  agents: AgentConfig[]
  authorizedUsers: string[]
  schedules: Array<{ agent: string; task: string; cron: string }>
}

const CONFIG_PATH = resolve(import.meta.dirname, '../../config/agents.json')

function loadConfig(): AgentsFile {
  if (!existsSync(CONFIG_PATH)) {
    logger.warn('config/agents.json not found — run `npm run setup` to create it')
    return { agents: [], authorizedUsers: [], schedules: [] }
  }
  return JSON.parse(readFileSync(CONFIG_PATH, 'utf-8'))
}

const config = loadConfig()

/** Agent lookup by name */
export const AGENTS: Record<string, AgentConfig> = Object.fromEntries(
  config.agents.map(a => [a.name, a]),
)

/** Reverse lookup: chat ID → agent name */
export const CHAT_TO_AGENT: Record<string, string> = Object.fromEntries(
  config.agents.map(a => [a.chatId, a.name]),
)

/** Authorized Telegram user IDs */
export const AUTHORIZED_USERS = config.authorizedUsers

/** Scheduled tasks */
export const SCHEDULES = config.schedules

/** Add a new agent to the config file */
export function registerAgent(agent: AgentConfig) {
  const fresh = loadConfig()
  // Don't duplicate
  if (fresh.agents.some(a => a.name === agent.name)) return
  fresh.agents.push(agent)
  writeFileSync(CONFIG_PATH, JSON.stringify(fresh, null, 2) + '\n', 'utf-8')
  // Update in-memory
  AGENTS[agent.name] = agent
  CHAT_TO_AGENT[agent.chatId] = agent.name
  logger.info({ agent: agent.name }, 'New agent registered')
}
